# SPDX-License-Identifier: AGPL-3.0-only
# Generated by scripts/homebrew-formula.mjs from the v260929215406.0.0 SHA256SUMS.
# Installs the signed, notarized darwin release bytes. No source build and no re-sign.
class AeonAgentd < Formula
  desc "PAIMOS AEON local harness supervisor"
  homepage "https://github.com/inspr-at/paimos"
  version "260929215406.0.0"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/inspr-at/paimos/releases/download/v260929215406.0.0/paimos-agentd-darwin-arm64"
      sha256 "64b2491f8657da67028cac27ff1e31b2be4a4ffec77d57974487dc048e4fdc17"
    end
    on_intel do
      url "https://github.com/inspr-at/paimos/releases/download/v260929215406.0.0/paimos-agentd-darwin-amd64"
      sha256 "b5662497a993684a4fcd292b8c0e6392292c5efffa482ad98daf4d5623984e53"
    end
  end

  def install
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "paimos-agentd-darwin-#{arch}" => "aeon-agentd"
  end

  test do
    assert_match "260929215406.0.0", shell_output("#{bin}/aeon-agentd --version")
  end
end
