# SPDX-License-Identifier: AGPL-3.0-only
# Generated by scripts/homebrew-formula.mjs from the v261009063244.0.0 SHA256SUMS.
# Installs the signed, notarized darwin release bytes. No source build and no re-sign.
class AeonAgentd < Formula
  desc "PAIMOS AEON local harness supervisor"
  homepage "https://github.com/inspr-at/paimos"
  version "261009063244.0.0"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/inspr-at/paimos/releases/download/v261009063244.0.0/paimos-agentd-darwin-arm64"
      sha256 "5b2204acfdd7f06167aa22d56b2d67b590902950c1ea7a998e1276cc23d97f53"
    end
    on_intel do
      url "https://github.com/inspr-at/paimos/releases/download/v261009063244.0.0/paimos-agentd-darwin-amd64"
      sha256 "9eb77eac908b9428b01107c9d48ab255db38a6bbf6102ae2d994ee7626088a0d"
    end
  end

  def install
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "paimos-agentd-darwin-#{arch}" => "aeon-agentd"
  end

  test do
    assert_match "261009063244.0.0", shell_output("#{bin}/aeon-agentd --version")
  end
end
