# SPDX-License-Identifier: AGPL-3.0-only
# Generated by scripts/homebrew-formula.mjs from the v261008161926.0.0 SHA256SUMS.
# Installs the signed, notarized darwin release bytes. No source build and no re-sign.
class AeonAgentd < Formula
  desc "PAIMOS AEON local harness supervisor"
  homepage "https://github.com/inspr-at/paimos"
  version "261008161926.0.0"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/inspr-at/paimos/releases/download/v261008161926.0.0/paimos-agentd-darwin-arm64"
      sha256 "9305debf17ae88893f5191ca3ca0408e306c39a04354e868e84eae8a9f8f264b"
    end
    on_intel do
      url "https://github.com/inspr-at/paimos/releases/download/v261008161926.0.0/paimos-agentd-darwin-amd64"
      sha256 "71afd6551bef58cdb137680a6415e3d06a75f3cd0d5c38b0ba9019b79aee968d"
    end
  end

  def install
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "paimos-agentd-darwin-#{arch}" => "aeon-agentd"
  end

  test do
    assert_match "261008161926.0.0", shell_output("#{bin}/aeon-agentd --version")
  end
end
